var pilot1 = new Pilot();
pilot1.firstName = "Lion";
pilot1.lastName = "Hack";
pilot1.pilotLicenseNumber = "0916652";
pilot1.exYears = 5.5;
pilot1.getInfo();
var airstared1 = new AirSteward();
airstared1.firstName = "Israel";
airstared1.lastName = "Israeli";
airstared1.originCountry = "Sweden";
airstared1.exYears = 2;
airstared1.class = "first";
airstared1.getInfo();
var groundsteward1 = new GroundSteward();
groundsteward1.firstName = "BOB";
groundsteward1.lastName = "Shalom";
groundsteward1.originCountry = "Israel";
groundsteward1.exYears = 10;
groundsteward1.job = "Manager";
groundsteward1.getInfo();
var passenger1 = new Passenger();
passenger1.firstName = "Igal";
passenger1.lastName = "Shapo";
passenger1.passportNumber = "065351254";
passenger1.getInfo();
//# sourceMappingURL=app.js.map